In [1]:
import numpy as np


In [6]:
#1D array
x=np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [5]:
#to create array from 1-100 with each value having diff of 3
x=np.arange(0,100,3,dtype=np.int64)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [8]:
# to check size of array
x=np.array([1,2,3,4,5,6,7,8])
x.shape

(8,)

In [9]:
#to reshape array
y=x.reshape(2,4)
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
y.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
#to create array of zeroes and ones 
ze=np.zeros((4,3),dtype=np.int64)
print("zeroes array")
print(ze)
print()
one=np.ones((4,3),dtype=np.int64)
print("ones array")
print(one)
print()

onezo=np.eye(4,4,dtype=np.int64)
print("both array")
print(onezo)
print()

zeroes array
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

ones array
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

both array
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]



In [27]:
#to make matrix with all entries with 8
x=np.full((4,3),4,dtype=np.int64)
print(x.reshape(3,2,2))
print(x.shape)

[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]
(4, 3)
